server:
  port: 9006                # 本服务启动端口

# Eureka服务注册相关配置
eureka:
  client:
    service-url:
      defaultZone: @eureka.host@   # Eureka Server地址（支持集群/逗号分隔/变量替换）
    registry-fetch-interval-seconds: 5 # 本地缓存服务列表刷新的时间，默认30s，这里设置为5秒（更快感知服务变化）
    healthcheck:
      enabled: true    # 开启健康检查（actuator/health）
  instance:
    prefer-ip-address: true     # 注册时显示IP（非主机名），兼容老版本
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name} # 实例唯一标识（IP:服务名）
    lease-expiration-duration-in-seconds: 9    # 超过9秒没收到心跳认为宕机（默认90s，缩短感知时间）
    lease-renewal-interval-in-seconds: 3       # 发送心跳的间隔（默认30s，缩短为3秒）
    non-secure-port: ${server.port}            # 注册的非安全端口
    health-check-url-path: /actuator/health    # 指定健康检查的URL

spring:
  application:
    name: config-server           # 服务名
  cloud:
    config:
      server:
        # 本地配置仓库/（已注释，当前用git）
        # native:
        #  search-locations: classpath:/shared
        git:
          uri: @config.git.url@               # Git配置仓库地址（变量替换）
          username: @config.git.username@     # Git用户名
          password: @config.git.password@     # Git密码
          search-paths:                       # 多个微服务的配置文件路径
            - ad
            - authority
            - boss
            - comment
            - course
            - front
            - gateway
            - message
            - oauth
            - order
            - pay
            - user
          default-label: main                 # 默认分支，推荐main（以前是master）
          basedir: @config.git.basedir@       # 本地拉取配置的目录
          clone-on-start: true                # 启动时克隆（拉取）Git配置
      label: main                             # 读取的分支

  rabbitmq:
    host: @mq.host@           # MQ主机
    port: @mq.port@           # MQ端口
    username: @mq.username@   # MQ用户名
    password: @mq.password@   # MQ密码

  main:
    allow-bean-definition-overriding: true    # 允许Spring Bean重名覆盖（开发常用）

# actuator相关配置（暴露监控/健康检查端点）
management:
  endpoints:
    web:
      exposure:
        include: "*"         # 全部端点都暴露
  endpoint:
    health:
      show-details: always   # 健康检查接口返回全部详细信息
